version: '3'
services:
  app:
    build: .
    ports:
      - "6868:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: alemeno-task
    depends_on:
      - db
    command: [ "./wait-for-it.sh" ]

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: alemeno-task
